# Generated by Django 4.0.3 on 2022-03-21 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mobile1', models.CharField(max_length=100)),
                ('mobile2', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('reference_name', models.CharField(max_length=100)),
                ('aadhar_number', models.CharField(max_length=100)),
                ('date_of_entered', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(upload_to='')),
                ('email_notifications', models.BooleanField(default=False)),
                ('sms_notifications', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=100)),
                ('date_of_entered', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuyerEntryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_commn', models.IntegerField()),
                ('unit_type', models.CharField(max_length=100)),
                ('unit_price', models.IntegerField()),
                ('buyer_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyerentry')),
            ],
        ),
    ]
