# Generated by Django 4.0.3 on 2022-03-17 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerentry',
            old_name='buyer_name',
            new_name='buyer',
        ),
    ]
