# Generated by Django 4.0.3 on 2022-03-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_rename_buyer_name_buyerentry_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyer',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
