# Generated by Django 4.0.3 on 2022-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
    ]
